import { Router, type IRouter } from "express";
import healthRouter from "./health";
import homesRouter from "./homes";
import staffRouter from "./staff";
import patientsRouter from "./patients";
import medicationsRouter from "./medications";
import incidentsRouter from "./incidents";
import dailyLogsRouter from "./daily-logs";
import shiftsRouter from "./shifts";
import dashboardRouter from "./dashboard";
import timePunchesRouter from "./time-punches";
import fraudAlertsRouter from "./fraud-alerts";
import emarRouter from "./emar";
import medicationSafetyRouter from "./medication-safety";
import medicationAdvancedRouter from "./medication-advanced";
import billingRouter from "./billing";
import integrationsRouter from "./integrations";
import workforceRouter from "./workforce";
import familyPortalRouter from "./family-portal";
import predictiveRouter from "./predictive";
import securityRouter from "./security";
import staffMessagingRouter from "./staff-messaging";
import appointmentsRouter from "./appointments";
import assignmentsRouter from "./assignments";
import transportationRouter from "./transportation";
import pushNotificationsRouter from "./push-notifications";
import organizationsRouter from "./organizations";
import seedDemoRouter from "./seed-demo";
import testAccountsRouter from "./test-accounts";
import devicesRouter from "./devices";
import stripeRouter from "./stripe";
import meetingsRouter from "./meetings";
import calendarSyncRouter from "./calendar-sync";
import crisisRouter from "./crisis";
import trainingRouter from "./training";
import censusRouter from "./census";
import admissionsRouter from "./admissions";
import treatmentPlansRouter from "./treatment-plans";
import progressNotesRouter from "./progress-notes";
import dischargeRouter from "./discharge";
import stateComplianceRouter from "./state-compliance";
import inspectorPortalRouter from "./inspector-portal";
import medicationLifecycleRouter from "./medication-lifecycle";
import medPassPinRouter from "./med-pass-pin";
import medAccessChallengeRouter from "./med-access-challenge";
import searchRouter from "./search";
import camerasRouter from "./cameras";
import supportTicketsRouter from "./support-tickets";
import adminRouter from "./admin";
import backupsRouter from "./backups";
import { logPhiAccess, trackSession, geofenceMiddleware, enforceIpWhitelist } from "../middlewares/security";
import { requireAuth } from "../middlewares/requireAuth";

const router: IRouter = Router();

router.use(healthRouter);
router.use(securityRouter);

const phiRoutes = Router();
phiRoutes.use(requireAuth);
phiRoutes.use(trackSession);
phiRoutes.use(enforceIpWhitelist);

phiRoutes.use("/patients", logPhiAccess("patient", "view"));
phiRoutes.use("/medications", logPhiAccess("medication", "view"));
phiRoutes.use("/emar", logPhiAccess("emar", "view"));
phiRoutes.use("/medication-safety", logPhiAccess("medication_safety", "view"));
phiRoutes.use("/medication-advanced", logPhiAccess("medication_advanced", "view"));
phiRoutes.use("/crisis", logPhiAccess("crisis", "view"));

phiRoutes.use(patientsRouter);
phiRoutes.use(medicationsRouter);
phiRoutes.use(emarRouter);
phiRoutes.use(medicationSafetyRouter);
phiRoutes.use(medicationAdvancedRouter);
phiRoutes.use(censusRouter);
phiRoutes.use(admissionsRouter);
phiRoutes.use(treatmentPlansRouter);
phiRoutes.use(progressNotesRouter);
phiRoutes.use(dischargeRouter);
phiRoutes.use(crisisRouter);
phiRoutes.use(medicationLifecycleRouter);

router.use(phiRoutes);

router.use(homesRouter);
router.use(staffRouter);
router.use(incidentsRouter);
router.use(dailyLogsRouter);
router.use(shiftsRouter);
router.use(dashboardRouter);
router.use(timePunchesRouter);
router.use(fraudAlertsRouter);
router.use(billingRouter);
router.use(integrationsRouter);
router.use(workforceRouter);
router.use(familyPortalRouter);
router.use(predictiveRouter);
router.use(staffMessagingRouter);
router.use(appointmentsRouter);
router.use(assignmentsRouter);
router.use(transportationRouter);
router.use(pushNotificationsRouter);
router.use(organizationsRouter);
router.use(seedDemoRouter);
router.use(stripeRouter);
router.use(meetingsRouter);
router.use(calendarSyncRouter);
router.use(testAccountsRouter);
router.use(devicesRouter);
router.use(trainingRouter);
router.use(medPassPinRouter);
router.use(medAccessChallengeRouter);
router.use(searchRouter);
router.use(camerasRouter);
router.use(supportTicketsRouter);
router.use(adminRouter);
router.use(backupsRouter);
router.use(stateComplianceRouter);
router.use(inspectorPortalRouter);

export default router;
